import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ViewStateProvider } from "@/lib/context/ViewContext";
import ThreeScene from "@/components/ThreeJs/ThreeScene";
import Objects from "@/components/ThreeJs/Objects";
import Control from "@/components/ThreeJs/Control";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        href="https://api.fontshare.com/v2/css?f[]=clash-display@200,300,400,500,600,700&display=swap"
        rel="stylesheet"
      />{" "}
      <ViewStateProvider>
        <body className={`${inter.className} overflow-x-hidden`}>
          {children}
          <ThreeScene>
            <color attach="background" args={["#000000"]} />
            <Objects color="#000000" position={[-1, 0, 0]} />
            <ambientLight />
            <Control />
          </ThreeScene>
        </body>
      </ViewStateProvider>
    </html>
  );
}
